# Generated by Django 4.2.5 on 2023-10-03 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='identificador',
        ),
    ]
